name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
    push:
        branches-ignore:
            - master
            - version-*

jobs:
    build-job:
        uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
        with:
            build-target: 'Docker'
            docker-username: ${{ github.actor }}
            strict-scanner: false # not all licenses present in the allowed list
        secrets:
            docker-password: ${{ secrets.GITHUB_TOKEN }}
            nvd-api-key: ${{ secrets.NVD_APIKEY }}